### ISSUE TITLE
QuranCode1433.full.zip request

### ISSUE THREAD

**Issue by Kouzeru** [heliwave/QuranCode#1]
Assalamu 'alaika

O brother, I had trouble downloading QuranCode1433.full.zip through QuranCode's server.
Perhaps there is an alternative link, which provides full speed, like GoogleDrive, Dropbox, etc.

Jazaka Allahu khairan katheera

**Comment by heliwave** [comment]
waAlaykum al-salam brother,
I have uploaded QuranCode1433.Full.zip to Sync.com
Here is the direct link:Sync | Secure cloud storage that protects your privacy

  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Sync | Secure cloud storage that protects your privacy
   |   |

  |

  |

 

Welcome :)
Ali
